### ISSUE TITLE
Performance issues in Firefox

### ISSUE THREAD

**Issue by Henni** [jbt/mdEdit#13]
Large markdown files like https://raw.githubusercontent.com/owncloud/news/master/README.md have very large input lag in firefox.

**Comment by jbt** [comment]
Wow yeah that is pretty terrible. Strange that Chrome is perfectly happy but firefox grinds to a halt. I shall do some profiling and see what's going on

**Comment by Henni** [comment]
@jbt thanks!

**Comment by jbt** [comment]
Looks like the performance of `.innerHTML` is absolutely terrible on firefox if you're replacing a ton of descendant elements. I have an idea, but I need to make sure it doesn't make perf a whole load _worse_ on other browsers.

**Comment by jbt** [comment]
Right I've done some rearranging in #16 that _seems_ to address this. Gonna play around on it a little bit more to make sure it's vaguely sensible

**Comment by Henni** [comment]
Definitely better than before.
Works great on Chrome 46 and Firefox 41
