### ISSUE TITLE
Which browsers does this library support?

### ISSUE THREAD

**Issue by Henni** [jbt/mdEdit#14]
A short documentation / sentence in the README about browser support (especially IE versions) would be great.
This information is interesting for contributors of this library and developers using mdEdit.

**Comment by jbt** [comment]
Good idea. I have to admit, I genuinely have no idea what the browser support is like, other than that it works pretty well in the latest chrome/firefox/safari/IE. I'll need to do some more testing to see what would break in older versions. Off the top of my head I think anything with decent ES5 support should work fine. How far back in IE versions are you interested in?

**Comment by Henni** [comment]
The project I'm using mdEdit in currently still supports IE8. (https://github.com/owncloud/notes)
But I would say dropping support for IE8 or even IE9 is fine.
BTW IE8 doesn't support ES5.

EDIT: i asked because of #15 where `classList` would be useful, but isn't supported by IE9 (http://caniuse.com/#feat=classlist)

**Comment by jbt** [comment]
I've been looking through and (without actually testing in IE8) these are some of the things I can see that would currently break in older browsers:
- addEventListener (easy to add attachEvent)
- Array.map / forEach (easy polyfill)
- Function.bind (easy polyfill)
- clipboardData (for paste event. I'm sure this can be worked around)

I don't think there's any reason why _not_ to support IE8 in terms of functionality. The only thing that could potentially hold it back would be performance, and the only way to know that is to try it out.

**Comment by Henni** [comment]
Another reason to not support IE8 is code complexity. Maintaining and contributing to the project might get more complicated and some contributors might even be scared off b all the polyfills.
IE8 support is dropped by Microsoft in January 2016

**Comment by jbt** [comment]
Yeah on reflection I'm thinking it wouldn't be a good idea to put a load of polyfills in there. Prism uses Array.map internally anyway. Realistically I think this is looking like "any browsers with decent ES5 support". So that'd be IE9+ and all the most recent of the other browsers. I'll stick something in the README.

**Comment by jbt** [comment]
Right, sorry it took so long (been super-busy with other stuff for last couple of weeks), but there we go, now should support IE9+ perfectly fine, and added note to that effect into readme.

**Comment by Henni** [comment]
Awesome!
