### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by jbrooksuk** [jbt/mdEdit#2]
Use Gulp to build mdEdit?

**Comment by jbt** [comment]
Possibly. This is all just very barebones atm based on a minimal-dependency skeleton I use for other projects. If it turns out to need anything more complicated in the future then possibly, but I kinda like how minimal and self-contained it is atm.

**Comment by Henni** [comment]
implemented in #12

**Comment by jbt** [comment]
Done thanks to @Henni! :tada: :tada:
