### ISSUE TITLE
How can I use API to move cursor?

### ISSUE THREAD

**Issue by greenlaw110** [jbt/mdEdit#23]
First, thanks for this neat tool, love it!

Now question: is there any API for me to move the cursor to somewhere e.g. the end of the document?

**Comment by greenlaw110** [comment]
Found it:

```
        editor = mdEdit(document.getElementById('code'), {
          change: function(content) {
            RiotControl.trigger('editor-updated', content)
          }
        })
        var len = editor.el.innerText.length
        editor.selMgr.setRange(len, len)
```

**Comment by jbt** [comment]
At some point I'll add a slightly nicer API for this - `selMgr` is a bit internal-feeling and there should probably just be a nice method directly on the `editor`
