### ISSUE TITLE
It looks like I can't use Prism line-numbers plugin

### ISSUE THREAD

**Issue by greenlaw110** [jbt/mdEdit#25]
Even I added `line-numbers` into `class` of `<pre>` tag it doesn't work. Any idea?

**Comment by jbt** [comment]
Just been looking into this. I'm guessing it's to do with the fact that `Prism.highlight(text, grammar)` doesn't run the various extra hooks that the line-numbers class uses. I'll have a look to see if I can add those in to make them work

**Comment by greenlaw110** [comment]
I think this is more complicated than I thought. What I need is not a line number for the entire page, but the capability to mark lines in code blocks

E.g. if I have the following md file:

![image](https://cloud.githubusercontent.com/assets/216930/15445977/cf315b18-1f52-11e6-9a24-0ea996e4dd32.png)

I expect to have line numbers in the rendered code block:

![image](https://cloud.githubusercontent.com/assets/216930/15445979/ec77d4fe-1f52-11e6-9199-e27687eff634.png)

**Comment by greenlaw110** [comment]
I think this should be an issue with markdown-it, not mdEdit

**Comment by greenlaw110** [comment]
Okay it's nether markdown-it issue nor mdEditor issue, the following code change in the [glue js](https://github.com/actframework/act-dockit/blob/master/src/main/resources/dockit/editor/tag/preview.tag.html#L48) take me to where I want:

Old code:

``` javascript
    var md = markdownit({
      html: true,
      highlight: function (code, lang) {
        if (languageOverrides[lang]) lang = languageOverrides[lang];
        if (lang && Prism.languages[lang]) {
          return Prism.highlight(code, Prism.languages[lang]);
        }
        return code;
      }
    }).use(markdownitFootnote);
```

New code:

``` javascript
    var md = markdownit({
      html: true,
      highlight: function (code, lang) {
        if (languageOverrides[lang]) lang = languageOverrides[lang];
        if (lang && Prism.languages[lang]) {
          var codeElement = document.createElement("code");
          codeElement.innerHTML = code;
          codeElement.className = 'language-' + lang + ' line-numbers';
          var preElement = document.createElement("pre");
          preElement.appendChild(codeElement);
          Prism.highlightElement(codeElement);
          return codeElement.innerHTML;
        }
        return code;
      }
    }).use(markdownitFootnote);
```

And now I get the line numbers in the rendering result:

![image](https://cloud.githubusercontent.com/assets/216930/15448471/0c07148a-1fa6-11e6-8b36-3c71261ed900.png)
