### ISSUE TITLE
Is this project still live?

### ISSUE THREAD

**Issue by greenlaw110** [jbt/mdEdit#26]
Still nobody is answer the issue submits :-(

I start to wondering if it is a wise decision to put my project on top of this one ...

**Comment by jbt** [comment]
Really sorry I haven't got round to responding to your issues yet - this is just a spare-time project and I've been really busy lately. I'll get back to them when I can in the next couple of days.

**Comment by greenlaw110** [comment]
I start to clean up the issues on my fork and keep pushing pull requests to you. At the moment the biggest concern is the [performance issue](https://github.com/jbt/mdEdit/issues/32). It would be great if you can get on top of that one when you got a bit time
